<?php

declare(strict_types=1);

namespace Juling\DevTools\Resolvers;

use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Juling\DevTools\Support\DevConfig;
use Juling\DevTools\Support\SchemaTrait;
use ReflectionClass;
use ReflectionException;
use ReflectionMethod;

class RouteResolver extends Foundation
{
    use SchemaTrait;

    /**
     * @throws ReflectionException
     */
    public function build(DevConfig $devConfig, array $data): void
    {
        $dirs = array_merge(
            glob(app_path('Api/*'), GLOB_ONLYDIR),
            glob(app_path('Bundles/*'), GLOB_ONLYDIR),
            glob(app_path('Modules/*'), GLOB_ONLYDIR)
        );
        foreach ($dirs as $dir) {
            $dist = $dir.'/Routes';
            $this->ensureDirectoryExists($dist);

            $controllers = glob($dir.'/Controllers/*Controller.php');
            $routes = $this->getRouteContent($this->getRoutes($controllers));
            file_put_contents($dist.'/route.gen.php', $this->getTemplate($routes));
        }
    }

    /**
     * @throws ReflectionException
     */
    private function getRoutes(array $files): array
    {
        $routes = [];

        $ignoreControllers = config('devtools.exclude_controllers');
        foreach ($files as $file) {
            $file = str_replace('/', '\\', $file);
            preg_match('/(app\\\\.+?\\\\(\w+)Controller)\.php/', $file, $matches);
            if (! in_array(Str::studly($matches[2]), $ignoreControllers)) {
                $class = ucfirst($matches[1]);
                $classRoutes = $this->reflectionRoutes($class);
                $routes = array_merge($routes, $classRoutes);
            }
        }

        return $routes;
    }

    /**
     * @throws ReflectionException
     */
    private function reflectionRoutes(string $class): array
    {
        $reflectionClass = new ReflectionClass($class);
        $methods = $reflectionClass->getMethods(ReflectionMethod::IS_PUBLIC);
        $methods = array_filter($methods, function ($item) use ($class) {
            return $item->class === $class;
        });

        $routes = [];
        foreach ($methods as $method) {
            $methodAttributes = $reflectionClass->getMethod($method->name)->getAttributes();
            if (isset($methodAttributes[0])) {
                $methodAttribute = $methodAttributes[0];
                if (! isset($methodAttribute->getArguments()['path'])) {
                    exit('Route path not found:'.$class.'@'.$method->name);
                }

                $httpMethod = Str::lower(Arr::last(explode('\\', $methodAttribute->getName())));
                $path = $methodAttribute->getArguments()['path'];
                $summary = $methodAttribute->getArguments()['summary'];
                $routes[] = [
                    'httpMethod' => $httpMethod,
                    'path' => $path === '/' ? $path : ltrim($path, '/'),
                    'class' => $class,
                    'action' => $method->name,
                    'summary' => $summary,
                ];
            }
        }

        return $routes;
    }

    private function getRouteContent(array $routes): string
    {
        $routeContent = '';
        foreach ($routes as $route) {
            $routeContent .= "\n// ".$route['summary'];
            $routeContent .= "\nRoute::{$route['httpMethod']}('{$route['path']}', [\\{$route['class']}::class, '{$route['action']}'])";
            if ($route['httpMethod'] === 'get') {
                $name = 'index';
                if ($route['path'] !== '/') {
                    $name = Str::replace('/', '.', $route['path']);
                }
                $routeContent .= "->name('$name')";
            }
            $routeContent .= ';';
        }
        $routeContent .= "\n";

        return $routeContent;
    }

    private function getTemplate($content): string
    {
        return <<<EOF
<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;
$content
EOF;
    }
}
