<?php

declare(strict_types=1);

namespace Juling\DevTools\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class GenPagesRoute extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'gen:pages:route';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle(): void
    {
        $viewPath = resource_path('views/pages');
        $routeFilePath = base_path('routes/pages.php');

        if (! File::isDirectory($viewPath)) {
            $this->error('The resources/views/pages directory does not exist.');

            return;
        }

        $files = File::allFiles($viewPath);
        $routeDefinitions = <<<EOF
<?php

// ==========================================================================
// Code generated by gen:pages:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;\n\n
EOF;

        foreach ($files as $file) {
            $relativePath = $file->getRelativePathname();
            $uri = str_replace('.blade.php', '', $relativePath);
            $uri = str_replace(DIRECTORY_SEPARATOR, '/', $uri);

            if (basename($uri) === 'index') {
                $uri = dirname($uri);
                $uri = ($uri === '.') ? '/' : $uri;
            }

            $relativePath = str_replace('.blade.php', '', $relativePath);
            $view = $name = 'pages.'.str_replace(['/', '\\'], '.', $relativePath);
            if (str_ends_with($name, '.index')) {
                $name = Str::substr($name, 0, -6);
            }

            $routeDefinitions .= "Route::view('$uri', '$view')->name('$name');\n";
        }

        File::put($routeFilePath, $routeDefinitions);

        $this->info('View routes generated successfully!');
        $this->comment("File created at: $routeFilePath");
    }
}
